.\" Manpage for memo.
.\" Any errors or typos, contact niko@ideabyte.net.

.TH man 1 "24 Oct 2014" "1.1" "memo man page"
.SH NAME
memo \- unix-style note-taking software
.SH SYNOPSIS
memo [OPTIONS]
.SH DESCRIPTION
Memo is a note-taking software for POSIX compatible operating systems.
The short notes are saved to user's home directory in ~/.memo file
by default.
.SH OPTIONS
.IP "-a <content> [yyyy-MM-dd]"
Add a new note
.IP "-d <id>"
Delete note by id
.IP -D
Delete all notes
.IP "-e <path>"
Export notes as html to a file
.IP "-f <search>"
Find notes by text search
.IP "-F <regex>"
Find notes by regular expression
.IP "-l <n>"
Show latest n notes
.IP "-m <id>"
Mark note status as done
.IP "-M <id>"
Mark note status as undone
.IP -p
Show current memo file path
.IP "-P [id]"
Show postponed or mark note as postponed
.IP -R
Delete all notes marked as done
.IP -s
Show all notes except postponed
.IP -T
Mark all notes as done
.IP -h
Show short help and exit. This page
.IP -V
Show version number of program
.SH EXAMPLES
Add a new note:
       memo -a "Remember to buy milk!"
.PP        
Add a new note with custom date:
       memo -a "File taxes" 2014-10-14
.PP
Search memos by string:
       memo -f buy
.PP
Output:
       4    2014-10-10    Remember to buy milk
.PP
Replace record 4 with new text:
       memo -d 4 -a "Remember to buy cheese"
.PP
Add note from stdin:
       echo "My new note" | memo
.PP
Mark note as postponed:
       memo -P 4
.PP
Show postponed notes:
       memo -P
.PP
Postponed notes are not shown with -s. Postponed note
can be marked as undone or done normally using -m or -M flag.
Only undone notes can be postponed.
.PP
It's possible to change the location (and name) of the .memo
file. Create $HOME/.memorc with a line MEMO_PATH=/path/you/would/like
, Memo will use that path instead of the default $HOME/.memo path.
.SH FILES
.I $HOME/.memo
.I $HOME/.memorc
.SH AUTHORS
Written by Niko Rosvall, help written by Jari Aalto.
.SH COPYRIGHT
Copyright (C) 2014 Niko Rosvall <niko@ideabyte.net>
.PP
Released under license GPL-3+. For more information, see
http://www.gnu.org/licenses
